//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastMinuteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offert
    {
        public long id { get; set; }
        public int idClientBusiness { get; set; }
        public string description { get; set; }
        public string title { get; set; }
        public long price { get; set; }
        public long quantity { get; set; }
        public System.DateTime deadlineTime { get; set; }
    }
}
